name: get badges

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Create Star Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.BADGES }}
          gistID: 8d156aec0df0935de687049ccb5c3615
          filename: star_badge.json
          label: Stars
          message: World
          color: red
      - name: Create Fork Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.BADGES }}
          gistID: cb4cc4e13327a55028a5549f485c9af2
          filename: fork_badge.json
          label: Fork
          message: World
          color: red
