- name: Create Awesome Badge
  uses: schneegans/dynamic-badges-action@v1.6.0
  with:
    auth: ${{ secrets.BADGES }}
    gistID: 8d156aec0df0935de687049ccb5c3615
    filename: star_badge.json
    label: Hello
    message: World
    color: orange
