- name: Create Awesome Badge
  uses: schneegans/dynamic-badges-action@v1.6.0
  with:
    auth: ${{ secrets.BADGES }}
    gistID: <gist-ID>
    filename: star_badge.json
    label: Hello
    message: World
    color: orange
